In [3]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [4]:
data = pd.read_csv("final_data.csv")

In [5]:
data.head()

Unnamed: 0  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0           0   0            5.1           3.5            1.4           0.2   
1           1   1            4.7           3.2            1.6           0.2   
2           2   2            4.9           3.1            1.5           0.1   
3           3   3            4.4           2.9            1.4           0.2   
4           4   4            5.0           3.4            1.5           0.2   

       Species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [6]:
data.drop(["Unnamed: 0","Id"],axis=1,inplace=True)

In [7]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.9           3.1            1.5           0.1  Iris-setosa
3            4.4           2.9            1.4           0.2  Iris-setosa
4            5.0           3.4            1.5           0.2  Iris-setosa

LABEL ENCODİNG

In [8]:
le=LabelEncoder()

In [9]:
le.fit_transform(data["Species"])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
data["Species"]=le.fit_transform(data["Species"])

In [11]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

VERİ KONTROLLERİ-
#TRAİN_TEST_SPLİT#

In [12]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [13]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int32
dtype: object

In [14]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(data.iloc[:,:-1],data.iloc[:,1],test_size=0.2)

In [17]:
X_train.value_counts()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
4.9            3.1           1.5            0.1             3
5.2            3.4           1.4            0.2             2
6.4            2.8           5.6            2.2             2
5.1            2.5           3.0            1.1             2
6.3            2.8           5.1            1.5             2
                                                           ..
5.5            2.5           4.0            1.3             1
               2.4           3.7            1.0             1
5.4            3.9           1.7            0.4             1
               3.7           1.5            0.2             1
7.9            3.8           6.4            2.0             1
Length: 117, dtype: int64

MODELİN OLUŞTURULMASI

In [18]:
import xgboost as xgb

C:\Users\SERKAN\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [19]:
xgb_cls=xgb.XGBClassifier(objective="multiclass:softmax",num_class=3)

In [20]:
xgb_cls.fit(X_train,y_train)

C:\Users\SERKAN\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\SERKAN\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[21:39:26] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=16,
              num_class=3, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, reg_lambda=1,
              scale_pos_weight=None, subsample=1, tree_method='exact',
              validate_parameters=1, verbosity=None)

In [21]:
X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
120       5.600000           2.8            4.9           2.0
122       6.000000           2.2            5.0           1.5
80        5.800000           2.6            4.0           1.2
60        5.600000           3.0            4.5           1.5
136       6.700000           3.3            5.7           2.5
40        5.000000           3.5            1.3           0.3
95        5.826347           2.9            4.5           1.5
75        5.900000           3.0            4.2           1.5
104       7.600000           3.0            6.6           2.1
42        5.000000           3.5            1.3           0.3
35        4.400000           3.0            1.3           0.2
82        5.500000           2.6            4.4           1.2
55        6.300000           3.3            4.7           1.6
32        5.000000           3.2            1.2           0.2
85        5.700000           3.0            4.2           1.2
89        6.200000           2.9            4.3           1.3
5         4.600000           3.4            1.4           0.3
12        4.300000           3.0            1.1           0.1
22        5.100000           3.5            1.4           0.3
108       7.700000           3.8            6.7           2.2
134       5.800000           2.7            5.1           1.9
138       6.300000           2.7            4.9           1.8
113       7.200000           3.0            5.8           1.6
126       6.200000           3.4            5.4           2.3
90        5.500000           2.4            3.8           1.1
3         4.400000           2.9            1.4           0.2
45        5.000000           3.3            1.4           0.2
57        6.900000           3.1            4.9           1.5
53        5.500000           2.3            4.0           1.3
73        5.200000           2.7            3.9           1.4
127       6.500000           3.2            5.1           2.0

In [22]:
preds=xgb_cls.predict(X_test)
preds

C:\Users\SERKAN\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


array([2.8, 2.2, 2.6, 3. , 3.3, 3.5, 2.9, 3. , 3. , 3.5, 3. , 2.6, 3.3,
       3.2, 3. , 2.9, 3.4, 3. , 3.5, 3.8, 2.7, 2.7, 3. , 3.4, 2.4, 2.9,
       3.2, 3.1, 2.3, 2.7, 3.2])

In [23]:
import numpy as np

In [24]:
np.array(y_test)

array([2.8, 2.2, 2.6, 3. , 3.3, 3.5, 2.9, 3. , 3. , 3.5, 3. , 2.6, 3.3,
       3.2, 3. , 2.9, 3.4, 3. , 3.5, 3.8, 2.7, 2.7, 3. , 3.4, 2.4, 2.9,
       3.3, 3.1, 2.3, 2.7, 3.2])

In [33]:
import xgboost as xgb
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix

In [34]:
xgb_cls = xgb.XGBClassifier(objective="multi:softmax",num_class=3)

In [35]:
xgb_cls.fit(X_train, y_train)

C:\Users\SERKAN\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\SERKAN\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):


[21:43:01] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=16,
              num_class=3, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, reg_lambda=1,
              scale_pos_weight=None, subsample=1, tree_method='exact',
              validate_parameters=1, verbosity=None)

In [36]:
preds = xgb_cls.predict(X_test)

In [37]:
accuracy_score(y_test,preds)

ValueError: continuous is not supported

In [38]:
confusion_matrix(y_test, preds)

ValueError: continuous is not supported